=== hmrc/cis-deductions-api/resources/public/api/conf/1.0/schemas/amendCisDeductions/amend_cis_deductions_request.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "title": "Amend CIS Deductions for Subcontractor\n",
  "description": "This endpoint allows as developer to amend a CIS deductions which has been previously populated",
  "type": "object",
  "properties": {
    "fromDate": {
      "description": "The CIS start date of a tax year.",
      "type": "string",
      "example": "2019-04-06"
    },
    "toDate": {
      "description": "CIS End date of the a tax year.",
      "type": "string",
      "example": "2020-04-05"
    },
    "contractorName": {
      "description": "The name of the contractor the subcontractor worked for.",
      "type": "string",
      "example": "J Smith Builders"
    },
    "employerRef": {
      "description": "The unique identifier contractor reference number.",
      "type": "string",
      "example": "135/AB56789"
    },
    "periodData": {
      "description": "List of the components that make up the overall deductions.",
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "deductionAmount": {
            "description": "The deducted amount. relating to self employment This value must be between 0 and 99999999999.99 up to 2 decimal places",
            "type": "number",
            "example": "5000.99"
          },
          "deductionFromDate": {
            "description": "The From date when the deduction was made",
            "type": "string",
            "example": "2019-04-04"
          },
          "deductionToDate": {
            "description": "The To date when the deduction was made",
            "type": "string",
            "example": "2020-04-05"
          },
          "costOfMaterials": {
            "description": "The cost of materials incurred for CIS",
            "type": "number",
            "example": "2000000.99"
          },
          "grossAmountPaid": {
            "description": "CIS deductions gross amount paid relating to self-employment. The value must be between 0 and 99999999999.99 up to 2 decimal places",
            "type": "number",
            "example": "500.99"
          }
        },
        "required": [
          "deductionAmount",
          "deductionFromDate",
          "deductionToDate",
          "costOfMaterials",
          "grossAmountPaid"
        ]
      }
    }
  },
  "required": [
    "fromDate",
    "toDate",
    "contractorName",
    "employerRef",
    "periodData"
  ]
}

=== hmrc/cis-deductions-api/resources/public/api/conf/1.0/examples/create_request.json
{
  "fromDate": "2020-04-06",
  "toDate": "2021-04-05",
  "contractorName": "ContractorA",
  "employerRef": "123/AB56797",
  "periodData": [
    {
      "deductionAmount": 355.00,
      "deductionFromDate": "2020-06-06",
      "deductionToDate": "2020-07-05",
      "costOfMaterials": 35.00,
      "grossAmountPaid": 1457.00
    }
  ]
}
