=== hmrc/cis-deductions-api/resources/public/api/conf/3.0/schemas/cis_deductions_retrieve/response.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "object",
  "properties": {
    "totalDeductionAmount":{
      "description": "The total amount of tax deducted by CIS contractors. The value must be between 0 and 99999999999.99 up to 2 decimal places.",
      "type": "number",
      "multipleOf": 0.01,
      "minimum": 0,
      "maximum": 99999999999.99,
      "example": 5000.99
    },
    "totalCostOfMaterials":{
      "description": "The total cost of materials incurred under CIS by the subcontractor across all of the CIS contractors that they worked for. This value must be between 0 and 99999999999.99 up to 2 decimal places.",
      "type": "number",
      "multipleOf": 0.01,
      "minimum": 0,
      "maximum": 99999999999.99,
      "example": 5000.99
    },
    "totalGrossAmountPaid":{
      "description": "The total gross amount paid by CIS contractors. The value must be between 0 and 99999999999.99 up to 2 decimal places.",
      "type": "number",
      "multipleOf": 0.01,
      "minimum": 0,
      "maximum": 99999999999.99,
      "example": 5000.99
    },
    "cisDeductions": {
      "description": "List of the components that make up the overall deductions.",
      "type": "array",
      "items": {
        "title": "item",
        "type": "object",
        "properties": {
          "fromDate": {
            "description": "CIS start date of a tax year.\n\nMust conform to the format `YYYY-MM-DD`",
            "type": "string",
            "format": "date",
            "example": "2020-04-06"
          },
          "toDate": {
            "description": "CIS end date of a tax year.\n\nMust conform to the format `YYYY-MM-DD`",
            "type": "string",
            "format": "date",
            "example": "2021-04-05"
          },
          "contractorName": {
            "description": "The name of the contractor the subcontractor worked for. Must not be empty or contain only whitespace.",
            "type": "string",
            "pattern": "^.{1,105}$",
            "example": "Some Contractor"
          },
          "employerRef": {
            "description": "A unique identifier, the contractor reference number.",
            "pattern": "^[0-9]{3}\\/[^ ].{0,9}$",
            "type": "string",
            "example": "123/AC80213"
          },
          "totalDeductionAmount": {
            "description": "The total amount of tax deducted by a CIS contractor. The value must be between 0 and 99999999999.99 up to 2 decimal places.",
            "type": "number",
            "multipleOf": 0.01,
            "minimum": 0,
            "maximum": 99999999999.99,
            "example": 5000.99
          },
          "totalCostOfMaterials": {
            "description": "The total cost of materials incurred under CIS by the subcontractor. This value must be between 0 and 99999999999.99 up to 2 decimal places.",
            "type": "number",
            "multipleOf": 0.01,
            "minimum": 0,
            "maximum": 99999999999.99,
            "example": 5000.99
          },
          "totalGrossAmountPaid": {
            "description": "The total gross amount paid by a CIS contractor. The value must be between 0 and 99999999999.99 up to 2 decimal places.",
            "type": "number",
            "multipleOf": 0.01,
            "minimum": 0,
            "maximum": 99999999999.99,
            "example": 5000.99
          },
          "periodData": {
            "description": "List of deductions.",
            "type": "array",
            "items": {
              "title": "item",
              "type": "object",
              "properties": {
                "deductionFromDate": {
                  "description": "The From date when the deduction was made within the CIS tax year period.\n\nMust conform to the format `YYYY-MM-DD`",
                  "type": "string",
                  "format": "date",
                  "example": "2020-07-06"
                },
                "deductionToDate": {
                  "description": "The To date when the deduction was made within the CIS tax year period.\n\nMust conform to the format `YYYY-MM-DD`",
                  "type": "string",
                  "format": "date",
                  "example": "2020-08-05"
              },
                "deductionAmount": {
                "description": "The amount of tax deducted by the contractor. This value must be between 0 and 99999999999.99 up to 2 decimal places.",
                "type": "number",
                "multipleOf": 0.01,
                "minimum": 0,
                "maximum": 99999999999.99,
                "example": 5000.99
              },
              "costOfMaterials": {
                  "description": "The cost of materials incurred under CIS. This value must be between 0 and 99999999999.99 up to 2 decimal places.",
                  "type": "number",
                  "multipleOf": 0.01,
                  "minimum": 0,
                  "maximum": 99999999999.99,
                  "example": 50.00
                },
                "grossAmountPaid": {
                  "description": "The gross amount paid under CIS. This value must be between 0 and 99999999999.99 up to 2 decimal places.",
                  "type": "number",
                  "multipleOf": 0.01,
                  "minimum": 0,
                  "maximum": 99999999999.99,
                  "example": 5000.99
                },
                "submissionDate": {
                  "description": "The date the deduction was submitted, in the format `YYYY-MM-DDThh:mm:ss.SSZ`",
                  "type": "string",
                  "format": "date-time",
                  "example": "2020-05-11T16:38:57Z"
                },
                "submissionId": {
                  "description": "The unique identifier for the submission.",
                  "type": "string",
                  "format": "uuid",
                  "example": "4557ecb5-fd32-48cc-81f5-e6acd1099f3c"
                },
                "source": {
                  "description": "The source of the data.",
                  "type": "string",
                  "enum": ["customer", "contractor"]
                }
              },
              "required": [
                "deductionFromDate",
                "deductionToDate",
                "submissionDate",
                "source"
              ]
            }
          }
        },
        "required": [
          "periodData",
          "fromDate",
          "toDate",
          "employerRef"
        ]
      }
    }
  },
  "required": [
    "cisDeductions"
  ]
}

=== hmrc/cis-deductions-api/resources/public/api/conf/3.0/examples/cis_deductions_retrieve/response.json
{
  "totalDeductionAmount": 12345.56,
  "totalCostOfMaterials": 234234.33,
  "totalGrossAmountPaid": 2342424.56,
  "cisDeductions" : [
    {
      "fromDate": "2020-04-06",
      "toDate": "2021-04-05",
      "contractorName": "contractor Name",
      "employerRef": "123/AA12345",
      "totalDeductionAmount": 3543.55,
      "totalCostOfMaterials": 6644.67,
      "totalGrossAmountPaid": 3424.12,
      "periodData": [
        {
          "deductionFromDate": "2020-04-06",
          "deductionToDate": "2020-05-05",
          "deductionAmount": 4654.78,
          "costOfMaterials": 4564.89,
          "grossAmountPaid": 7878.67,
          "submissionDate": "2020-05-11T16:38:57Z",
          "submissionId": "4557ecb5-fd32-48cc-81f5-e6acd1099f3c",
          "source": "customer"
        },
        {
          "deductionFromDate": "2020-05-06",
          "deductionToDate": "2020-06-05",
          "deductionAmount": 355.00,
          "costOfMaterials": 35.00,
          "grossAmountPaid": 1457.00,
          "submissionDate": "2020-05-11T16:38:57Z",
          "source": "contractor"
        }
      ]
    },
    {
      "fromDate": "2020-04-06",
      "toDate": "2021-04-05",
      "contractorName": "Soylent Solutions",
      "employerRef": "123/TW44355",
      "totalDeductionAmount": 3543.55,
      "totalCostOfMaterials": 6644.67,
      "totalGrossAmountPaid": 3424.12,
      "periodData": [
        {
          "deductionFromDate": "2020-07-06",
          "deductionToDate": "2020-08-05",
          "deductionAmount": 60.00,
          "costOfMaterials": 35.00,
          "grossAmountPaid": 1457.00,
          "submissionDate": "2020-05-11T16:38:57Z",
          "source": "contractor"
        },
        {
          "deductionFromDate": "2020-09-06",
          "deductionToDate": "2020-10-05",
          "deductionAmount": 60.00,
          "costOfMaterials": 35.00,
          "grossAmountPaid": 1457.00,
          "submissionDate": "2020-05-11T16:38:57Z",
          "source": "contractor"
        }
      ]
    }
  ]
}
